# generated by mBlock5 for CyberPi
# codes make you happy

import event, time, cyberpi, mbot2, mbuild

@event.start
def on_start():
    cyberpi.console.println("Hallo Philipp!")
    cyberpi.console.print("Bitte  bot auf Boden und Taste A drücken!")
    if cyberpi.controller.is_press('a'):
      mbot2.backward(50)
      cyberpi.led.show('green green green green green')
      if mbuild.ultrasonic2.get(1) < 10:
        mbot2.forward(20, 3)
        cyberpi.led.show('red red red red red')
        mbot2.turn(-90)