# generated by mBlock5 for CyberPi
# codes make you happy

import event, time, cyberpi, mbuild, mbot2

@event.start
def on_start():
    cyberpi.console.println("Hallo Philipp!")
    cyberpi.console.print("Bitte  bot auf Boden und Taste A pressen!")

@event.is_press('a')
def is_btn_press():
    while True:
      while not mbuild.ultrasonic2.get(1) < 10:
        mbot2.forward(50)

      mbot2.straight(15)
      mbot2.turn(-90)

