# generated by mBlock5 for CyberPi
# codes make you happy

import event, time, cyberpi, mbot2

@event.is_press('a')
def is_btn_press():
    mbot2.forward(50, 3)
    mbot2.turn(-90)
    mbot2.forward(50, 3)
    mbot2.turn(90)