# generated by mBlock5 for CyberPi
# codes make you happy

import event, time, cyberpi
import time

@event.is_anticlockwise
def on_is_anticlockwise():
    for count in range(3):
      cyberpi.led.on(208, 159, 1, 5)
      time.sleep(0.2)
      cyberpi.led.on(0, 0, 0, 5)
      time.sleep(0.2)

@event.is_clockwise
def on_is_clockwise1():
    for count2 in range(3):
      cyberpi.led.on(208, 159, 1, 1)
      time.sleep(0.2)
      cyberpi.led.on(0, 0, 0, 1)
      time.sleep(0.2)