# generated by mBlock5 for CyberPi
# codes make you happy

import event, time, cyberpi

@event.start
def on_start():
    cyberpi.console.println("Willkommen!")
    cyberpi.console.println(cyberpi.get_battery())
    cyberpi.console.println("Zum Start Taste A Druecken!")