# generated by mBlock5 for CyberPi
# codes make you happy

import event, time, cyberpi, mbot2, mbuild, random
import time
# initialize variables
equalize = 0

@event.start
def on_start():
    global equalize
    cyberpi.console.println("Willkommen! ")
    time.sleep(1)
    cyberpi.console.clear()
    cyberpi.console.println("Batteriestatus:")
    cyberpi.console.println(cyberpi.get_battery())
    time.sleep(1)
    cyberpi.console.clear()
    cyberpi.console.print("Zum Programmstart Teste A (Rechteck) drücken!")
    cyberpi.audio.set_vol(100)

@event.is_press('a')
def is_btn_press():
    global equalize
    while True:
      mbot2.forward(50)
      if mbuild.ultrasonic2.get(1) < 10:
        equalize = random.randint(1, 2)
        cyberpi.console.println(equalize)
        if equalize > 1:
          mbot2.forward(0, 1)
          cyberpi.led.on(208, 2, 27, "all")
          time.sleep(1)
          cyberpi.led.on(0, 0, 0, "all")
          cyberpi.audio.play_music(60, 0.25)
          mbot2.turn(-90)
          mbot2.forward(50, 2)
          cyberpi.led.on(208, 2, 27, "all")
          time.sleep(0.5)
          cyberpi.led.on(0, 0, 0, "all")
          mbot2.turn(90)

        else:
          mbot2.forward(0, 1)
          cyberpi.led.on(208, 2, 27, "all")
          cyberpi.audio.play_music(60, 0.25)
          mbot2.turn(90)
          mbot2.forward(50, 2)
          cyberpi.led.on(208, 2, 27, "all")
          time.sleep(0.5)
          cyberpi.led.on(0, 0, 0, "all")
          mbot2.turn(-90)

      time.sleep(0.2)

@event.is_waveleft
def on_is_waveleft():
    global equalize
    for count in range(3):
      cyberpi.led.on(208, 170, 1, 1)
      time.sleep(0.2)
      cyberpi.led.on(0, 0, 0, 1)
      time.sleep(0.2)

@event.is_waveright
def on_is_waveright1():
    global equalize
    for count2 in range(3):
      cyberpi.led.on(208, 170, 1, 5)
      time.sleep(0.2)
      cyberpi.led.on(0, 0, 0, 5)
      time.sleep(0.2)

