# Ab hier könnt ihr euren Code einfügen
# generated by mBlock5 for CyberPi
# codes make you happy

import event, time, cyberpi
import time

@event.start
def on_start():
    time.sleep(1)
    cyberpi.led.play('rainbow')
# Hier erzeugen wir einen merge konflikt

# hier ist der zweite kommentar

# Neuer Kommentar