# generated by mBlock5 for CyberPi
# codes make you happy

import event, time, cyberpi
# initialize variables
Batterie = 0

@event.start
def on_start():
    global Batterie
    cyberpi.console.println("Willkommen!")
    cyberpi.console.println(cyberpi.get_battery())
    cyberpi.console.println("Startinstruktionen")