# generated by mBlock5 for CyberPi
# codes make you happy

import event, time, cyberpi
import time

@event.is_anticlockwise
def on_is_anticlockwise():
    cyberpi.led.off(1)
    for count in range(3):
      cyberpi.led.on(255, 187, 2, 1)
      time.sleep(1)
      cyberpi.led.on(0, 0, 0, 1)
      cyberpi.led.off(1)
      time.sleep(1)

@event.is_clockwise
def on_is_clockwise1():
    cyberpi.led.off(5)
    for count2 in range(3):
      cyberpi.led.on(255, 196, 2, 5)
      time.sleep(1)
      cyberpi.led.on(0, 0, 0, 5)
      cyberpi.led.off(5)
      time.sleep(1)
